# Generated by Django 5.2.4 on 2026-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_certificate_education_experience_hobby_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
